version: '2.0'
services:
  mserver:
    build:
      context: ..
      dockerfile: ./docker/server/Dockerfile
    ports: 
      - "25565:25565"
    tty: true  
    stdin_open: true
  testproxy:
    build:
      dockerfile: ./docker/proxy/Dockerfile
      context: ..
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "25566:25566"
    command: sh -c "sleep 5s && python3 /proxy/minecruft/Minecruft_Main.py proxy /proxy/configs/aes_ecb_key.bin 172.17.0.1 25565 9001 /proxy/configs/client_decoder_actions_v12.2.json /proxy/configs/client_encoder_actions_v12.2.json /proxy/configs/hmm/Clientbound/spawning.txt.bin_L4" 
  sshproxy:
    build: 
      dockerfile: ./docker/ssh/Dockerfile
      context: ..
    depends_on: 
      - "testproxy"
    tty: true 
    cap_add:
      - NET_ADMIN
    network_mode: service:testproxy
    command: sh -c "iptables -A OUTPUT -p tcp --tcp-flags RST RST -j DROP && /usr/sbin/sshd -o AllowTcpForwarding=yes -h /root/.ssh/id_rsa && ip a && ssh -o StrictHostKeyChecking=no -D 0.0.0.0:9001 127.0.0.1 && tail -f /dev/null"
  testclient: 
    build: 
      dockerfile: ./docker/client/Dockerfile
      context: ..
    network_mode: host 
    command: sh -c "sleep 8s && python3 /client/minecruft/Minecruft_Main.py client /client/configs/aes_ecb_key.bin 127.0.0.1 25566 9001 /client/configs/client_encoder_actions_v12.2.json /client/configs/client_decoder_actions_v12.2.json /client/configs/hmm/Serverbound/traveling.txt.bin_L3"
      
 
